Graph visualization
maddataanalyst/hextractor pull request #9
Opened 2024-10-15 14:29 UTC by maddataanalyst

Added:
1. Visualization config.
2. Validation for config.
3. Graph visualization builder.
4. Tests for all mentioned elements.
5. Tutorial notebook + html file with finished visualization.

2024-11-15 10:54 UTC, mmalczewski requested changes
Looks good. :+1: 
I would make above adjustments, but, as they are really small or trivial, it's up to you to decide.

2025-01-05 09:05 UTC, maddataanalyst commented on tests/test_visualization.py
> +        ValueError, match="Edge type \('type1', 'rel', 'type2'\) is missing."
Thanks, done.

2025-01-05 09:05 UTC, maddataanalyst commented on tests/test_visualization.py
> +    # given
Sure, changed this, done.

2025-01-05 09:08 UTC, maddataanalyst commented on hextractor/structures.py
> +    )
Good idea, very useful, when executing this in different environments (notebook, script, etc.). Done.

2025-01-05 09:09 UTC, maddataanalyst commented on tests/test_visualization.py
> +        _ = VisualizationBuilder.build_visualization(
Indeed, `_ = ...` is redundant. Changed. Thanks.

2025-01-05 09:15 UTC, merged